### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by avatar-lavventura** [MrKiven/Todo.py#12]
I am getting following error:

```
$ pip install todos
Collecting todos
  Downloading todos-0.2.1.tar.gz (5.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/alper/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/mx/m3c2fd193h169gg6nd5x3p480000gn/T/pip-install-n7p3ttka/todos_1acfca12108e4445ba22239d064b0a9e/setup.py'"'"'; __file__='"'"'/private/var/folders/mx/m3c2fd193h169gg6nd5x3p480000gn/T/pip-install-n7p3ttka/todos_1acfca12108e4445ba22239d064b0a9e/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/mx/m3c2fd193h169gg6nd5x3p480000gn/T/pip-pip-egg-info-pbpz7mzu
         cwd: /private/var/folders/mx/m3c2fd193h169gg6nd5x3p480000gn/T/pip-install-n7p3ttka/todos_1acfca12108e4445ba22239d064b0a9e/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/mx/m3c2fd193h169gg6nd5x3p480000gn/T/pip-install-n7p3ttka/todos_1acfca12108e4445ba22239d064b0a9e/setup.py", line 20, in <module>
        with open("README.md") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/33/a7/083d67ca6cb910122d3199e93dfb0a5fea1a34b935709954a06c122986f7/todos-0.2.1.tar.gz#sha256=b4ac7eeb735d7eca8500478950e7da97592c6626597e9d29b190e81d9d199422 (from https://pypi.org/simple/todos/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading todos-0.2.0.tar.gz (5.0 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/alper/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/mx/m3c2fd193h169gg6nd5x3p480000gn/T/pip-install-n7p3ttka/todos_58004c911964447d9e850d980db0ecf4/setup.py'"'"'; __file__='"'"'/private/var/folders/mx/m3c2fd193h169gg6nd5x3p480000gn/T/pip-install-n7p3ttka/todos_58004c911964447d9e850d980db0ecf4/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/mx/m3c2fd193h169gg6nd5x3p480000gn/T/pip-pip-egg-info-7zgq87lm
         cwd: /private/var/folders/mx/m3c2fd193h169gg6nd5x3p480000gn/T/pip-install-n7p3ttka/todos_58004c911964447d9e850d980db0ecf4/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/mx/m3c2fd193h169gg6nd5x3p480000gn/T/pip-install-n7p3ttka/todos_58004c911964447d9e850d980db0ecf4/setup.py", line 25, in <module>
        long_description=open("README.md").read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/25/9f/b0a465a78d3fd20499fd0511f7505c5714a48a11e2e6a703501916760d48/todos-0.2.0.tar.gz#sha256=4a222810edc8f718b786717cce8784a424f2ff1a439106ed7c2d1048e5cb06e8 (from https://pypi.org/simple/todos/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement todos
ERROR: No matching distribution found for todos

```

**Comment by berengamble** [comment]
I have this problem as well!
